# Generated by Django 2.0.7 on 2018-07-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20180718_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date created')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creadBy', to='life.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchasedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedBy', to='life.User'),
        ),
    ]
