# Generated by Django 2.0.7 on 2018-07-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20180722_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='createdBy',
            new_name='addedBy',
        ),
    ]
