# Generated by Django 2.0.7 on 2018-07-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20180723_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('need', 'need'), ('have', 'have'), ('history', 'history')], default='need', max_length=10),
        ),
    ]
